# SQLite version 3.x on development and test
sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *sqlite
  database: db/development.sqlite3

test:
  <<: *sqlite
  database: db/test.sqlite3

# PostgreSQL on production
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
